services:
  MongoConfig:
    factory:
      class: ../../../context/Shared/infrastructure/persistance/mongoose/MongooseConfigFactory
      method: 'create'

  ConnectionManager:
    factory:
      class: ../../../context/Shared/infrastructure/persistance/mongoose/MongooseClientFactory
      method: 'createClient'
    arguments: ['@MongoConfig']

  Feed.domain.FeedRepository:
    class: ../../../context/Feed/infrastructure/MongooseFeedRepository
    arguments: ['@ConnectionManager']

  Feed.application.FeedCreator:
    class: ../../../context/Feed/application/FeedCreator
    arguments: ['@Feed.domain.FeedRepository']
