services:
  MongoConfig:
    factory:
      class: ../../../context/Shared/infrastructure/persistance/mongo/MongoConfigFactory
      method: 'create'

  ConnectionManager:
    factory:
      class: ../../../context/Shared/infrastructure/persistance/mongo/MongoClientFactory
      method: 'create'
    arguments: ['@MongoConfig']

  Feed.domain.FeedRepository:
    class: ../../../context/Feed/infrastructure/MongoFeedRepository
    arguments: ['@ConnectionManager']

  Feed.application.FeedCreator:
    class: ../../../context/Feed/application/FeedCreator
    arguments: ['@Feed.domain.FeedRepository']
