services:
  controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  controllers.FeedPutController:
    class: ../../controllers/FeedPutController
    arguments: ['Feed.application.FeedCreator']
